version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx_container
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./public:/var/www/html/public
    depends_on:
      - php
      - nextjs

  nextjs:
    image: node:18
    container_name: nextjs_container
    working_dir: /var/www/html/frontend
    volumes:
      - ./frontend:/var/www/html/frontend
    command: sh -c "npm install && npm run dev"
    ports:
      - "${NEXTJS_PORT}:3000"

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_container
    volumes:
      - .:/var/www/html
    environment:
      DATABASE_URL: "mysql://${DB_USER}:${DB_PASSWORD}@mysql:3306/${DB_NAME}"

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: mysql
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${PHPMYADMIN_PORT}:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
