### Obter dados do cidadão pelo NIS
GET http://localhost:8080/api/citizen/01280237578
Accept: application/json

###

### Criar um novo cidadão
POST http://localhost:8080/api/citizen
Content-Type: application/json
Accept: application/json

{
  "name": "Fulano de Tal"
}

###

### Validar NIS
POST http://localhost:8080/api/validate
Content-Type: application/json
Accept: application/json

{
  "nis": "01280237578"
}